export const SORT_BY_PRICE_DESC = "SORT_BY_PRICE_DESC";
export const SORT_BY_PRICE_ASC = "SORT_BY_PRICE_ASC";
export const SORT_BY_RATING_DESC = "SORT_BY_RATING_DESC";
export const SORT_BY_RATING_ASC = "SORT_BY_RATING_ASC";